#!/bin/bash

# Welcome script for MittFortum Development Container
# This displays helpful information when the container starts

echo ""
echo "🏠 Welcome to MittFortum Home Assistant Development Container!"
echo ""
echo "📍 Container setup complete. You're ready to develop!"
echo ""
echo "🚀 Quick Start:"
echo "   1. Configure secrets: cp .devcontainer/config/secrets.yaml.template .devcontainer/config/secrets.yaml"
echo "   2. Edit secrets.yaml with your MittFortum credentials"
echo "   3. Run tests: .devcontainer/test-integration.sh"
echo "   4. Start HA: .devcontainer/start-hass.sh"
echo "   5. Open http://localhost:8123"
echo ""
echo "🛠️  VS Code Tasks (Ctrl+Shift+P → Tasks: Run Task):"
echo "   • Start Home Assistant"
echo "   • Run Tests"
echo "   • Lint with Ruff"
echo "   • Type Check with Pyrefly"
echo "   • Run All Checks"
echo ""
echo "📝 Key Files:"
echo "   • Integration: custom_components/mittfortum/"
echo "   • Tests: tests/"
echo "   • HA Config: .devcontainer/config/"
echo "   • Documentation: .devcontainer/README.md"
echo ""
echo "🔧 Command Line Tools:"
echo "   pytest              # Run tests"
echo "   ruff check .        # Lint code"
echo "   ruff format .       # Format code"
echo "   pyrefly .           # Type check"
echo "   pre-commit run --all-files  # Run all hooks"
echo ""
echo "💡 Need Help?"
echo "   • Check .devcontainer/README.md for detailed instructions"
echo "   • Check DEVELOPMENT.md for development workflow"
echo "   • Use VS Code debugger for complex issues"
echo ""
